### ISSUE TITLE
python setup.py install needs /p:TargetFrameworkVersion="v4.5"

### ISSUE THREAD

**Issue by Paradoxeuh** [pythonnet/pythonnet#477]
Hi

### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Ubuntu 16.04 (VM Google Compute)

### Details

It has been impossible to install pythonnet with pip install pythonnet or python setup.py install without adding /p:TargetFrameworkVersion="v4.5" to the setup.py.
Without this line I have :

CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

Is that a normal behavior ?

Cheers

**Comment by denfromufa** [comment]
You likely have an old Mono version, search the issue tracker here for the same error.
If you install Mono 5.0 (released couple weeks ago), then you need to install from master branch.

**Comment by Paradoxeuh** [comment]
My mono is 4.2.1. Is that considered too old? I read that pythonnet was not ready yet for Mono 5.0 (even in master). Is that true?

Thanks for your answer

**Comment by denfromufa** [comment]
Master works with Mono 5.0:

https://github.com/pythonnet/pythonnet/pull/471

**Comment by denfromufa** [comment]
Pythonnet 2.3.0 works with Mono 4.8.

**Comment by Paradoxeuh** [comment]
Thank you very much for those explanations 👍

**Comment by vmuriart** [comment]
Looks like we might need a minor or patch release soon-ish

**Comment by denfromufa** [comment]
Agreed, maybe this weekend?
