### ISSUE TITLE
CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, Default, Latest or a valid version i n range 1 to 7.1. [X:\pythonnet-master\src\runtime\Python.Runtime.csproj]

### ISSUE THREAD

**Issue by fjing1** [pythonnet/pythonnet#1035]
### Environment

-   Pythonnet version: 
-   Python version:3.6.8
-   Operating System:windows

### Details
I am trying to install Pythonnet 

    _TODO_
I downloaded the Pythonnet, unziped, in where I downloaded. Go to windows powershell, I typed cmd, dir, setup.py install
```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.
CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, Default, Latest or a valid version in
range 1 to 7.1. [X:\pythonnet-master\src\runtime\Python.Runtime.csproj]
X:\pythonnet-master\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Ut
ilities.ToolLocationHelper could not find ildasm.exe. [X:\pythonnet-master\src\clrmodule\clrmodule.csproj]
"X:\pythonnet-master\pythonnet.sln" (Build target) (1) ->
"X:\pythonnet-master\src\runtime\Python.Runtime.csproj" (default target) (2) ->
(CoreCompile target) ->
  CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, Default, Latest or a valid version i
n range 1 to 7.1. [X:\pythonnet-master\src\runtime\Python.Runtime.csproj]

"X:\pythonnet-master\pythonnet.sln" (Build target) (1) ->
"X:\pythonnet-master\src\clrmodule\clrmodule.csproj" (default target) (6) ->
(RGieseckeDllExport target) ->
  X:\pythonnet-master\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.
Utilities.ToolLocationHelper could not find ildasm.exe. [X:\pythonnet-master\src\clrmodule\clrmodule.csproj]

    0 Warning(s)
    2 Error(s)
```python
    print('TODO')
```

**Comment by fjing1** [comment]
I am a noob. Sorry for the messed issue

**Comment by fjing1** [comment]
I dont know my version of pythonnet, how can I find out? I just downloaded the pythonnet-master

**Comment by filmor** [comment]
> I dont know my version of pythonnet, how can I find out? I just downloaded the pythonnet-master
Then that's your version.

If your compiler doesn't work with C# 7.3 (that's what it's complaining about), then you must get a newer version of Visual Studio, at least 2017 15.7.
