### ISSUE TITLE
Add support for Python 3.14

### ISSUE THREAD

**Issue by freakboy3742** [pythonnet/pythonnet#2610]
Python.net's `requires-python` places a hard upper pin on `<3.14`. 

Python 3.14 is nearing release; RC1 is out, which indicates that ABI stability now exists.

It would be desirable for Python.net to support the upcoming Python release.

**Comment by EliaOndacs** [comment]
hey, hello, as of right now i'm writing this python 3.14 released, and i unexpectedly ran into this problem of pythonnet not supporting python 3.14, so i'm running into this problem too, (runtime error while trying to run a python script that is using pythonnet), i wonder how long it takes to update it for python 3.14 considering its release-candidates and pre-releases have been out for a while

**Comment by filmor** [comment]
Any help is appreciated. There is a branch you can test (https://github.com/pythonnet/pythonnet/pull/2611), but our CI is currently thoroughly broken and I haven't found the time to fix it, yet.

**Comment by freakboy3742** [comment]
@filmor I'm unfortunately not in a position to help directly - but if this is a situation that can be fixed by throwing money at someone who *does* have the skills to investigate the problem, I *might* be able to help. If that's the case, let me know.

**Comment by NasirNS45** [comment]
Any update on this? Ran into the same issue while installing awsebcli

**Comment by filmor** [comment]
Work is happening in #2611. It works in general, but there are at least two crashes that I (or someone who wants to dive in) have to investigate.

**Comment by andre-romano** [comment]
Pythonnet building is crashing in Windows env for Python 3.13.9 as well (similarly to version 3.14)

**Comment by filmor** [comment]
It is not.

1. Please don't cross post. If you have an issue, open one, don't comment in two unrelated threads.
2. Please add more data than "does not work". We are well aware that compiling with .NET >6 is problematic, and there is work going on to fix this (or rather, it is fixed on master but not all tests pass). It is unnecessary to compile Python.NET if you don't want to set up the outdated .NET 6 SDK, you can just use the precompiled Nuget or wheel packages.

**Comment by Houbein** [comment]
Installing pythonnet under Python 3.14 now just installs 3.0.0rc6, the last version not to enforce a max Python version. 
This happens quietly, not informing the user that they are installing a very old version. 
Please make it a priority to fix this.

**Comment by filmor** [comment]
3.1.0rc0 is out now with the Python 3.14 support merged. Please test and report back. I still have not found time to fix the CI completely, which is a prerequisite for me to cut this as a full release.

**Comment by freakboy3742** [comment]
I've done some ad-hoc testing with Toga, and it appears to be working with Python 3.14.3 on both x86_64 and ARM64. I haven't been able to run the full Toga test suite, but that's due to a known Toga problem, not a Python.net problem.

**Comment by mflova** [comment]
I was experimenting with it. Is it supposed to also work with `3.14t`?

**Comment by stefsmeets** [comment]
> 3.1.0rc0 is out now with the Python 3.14 support merged. Please test and report back. I still have not found time to fix the CI completely, which is a prerequisite for me to cut this as a full release.

Thanks, just tested this on our [Python SDK](https://github.com/PalmSens/PalmSens_SDK/tree/main/python). It passes the entire test suite on Fedora x64, Windows x64, and Raspbian (arm).

**Comment by manu-aesim** [comment]
I’ve conducted some testing with our Python module and can confirm that our entire test suite passes on macOS ARM, Ubuntu ARM, Ubuntu x64, and Windows x64, using Python 3.14.

**Comment by filmor** [comment]
@mflova No, we do not support free-threading. Feel free to try it, though. It might just require a few additional locks, but it could also require a major rework.

**Comment by danielhrisca** [comment]
The release notes for 3.1.0 rc0 release notes say that python 3.14 is supported https://github.com/pythonnet/pythonnet/releases/tag/v3.1.0-rc0 but pyproject.toml was not updated to include 3.14 https://github.com/pythonnet/pythonnet/blob/fc6c9e9f79d71e2a99a9c50a594127509fb5ff8d/pyproject.toml#L30

**Comment by filmor** [comment]
@danielhrisca Thanks, this is fixed now. I have also removed the unsupported versions from it. As far as I know, the trove classifiers are purely informational, though.

**Comment by MarkelJaure** [comment]
Hello, I'm very interested in using pythonnet in Python 3.14 because I believe it could be a solution for accessing CPU temperature data from Windows. Is there any information on when this release might be available?

**Comment by alexchandel** [comment]
`3.1.0rc0` works for me, I'd say release it.  `pythonnet` is the critical dependency for [pywebview](https://pywebview.flowrl.com/guide/installation.html).

**Comment by spkl** [comment]
> 3.1.0rc0 is out now with the Python 3.14 support merged. Please test and report back. I still have not found time to fix the CI completely, which is a prerequisite for me to cut this as a full release.

Thank you @filmor - I tested with 3.1.0rc0 but ran into an issue. We are using .NET objects with dynamically determined properties that are accessed from Python. Maybe you remember the dynamic.py file you created for #72 , our approach is similar. Both ways don't work anymore with 3.1.0rc0, but they do work with 3.0.5.
Python 3.12, pythonnet 3.0.5 - working
Python 3.12, pythonnet 3.1.0rc0 - not working
Python 3.14, pythonnet 3.1.0rc0 - not working

When trying to access a dynamic property, I get `AttributeError: 'Class1' object has no attribute 'SomePropertyFromDynamicObject'`. It seems like the injected `__getattr__` function is not called.

I have attached a C# project and python script to reproduce the issue. Build the C# solution, then run the test_dynamic_access.py script. It tests the DynamicObject-based approach, as well as our own, simplified version of it.

[DynamicObjectIssueRepro.zip](https://github.com/user-attachments/files/26114160/DynamicObjectIssueRepro.zip)

**Comment by filmor** [comment]
Thank you for the observation. Would you mind opening a dedicated issue for that?

**Comment by spkl** [comment]
Created #2696 as requested :)

**Comment by greateggsgreg** [comment]
Been testing this on a sizable project for a few weeks and it's been working great.
OS: Ubuntu 25.10
Python 3.14.3 (standard)
dotnet 8

**Comment by MischaPanch** [comment]
Hi. Any chance you could release this? With the pre-release out our users always have to add `--prelease=allow` to their installation commands when installing on 3.14

**Comment by alexchandel** [comment]
@MischaPanch They don't appear to want to merge until `test_getting_overloaded_method_binding_does_not_leak_memory()` is fixed.

**Comment by MischaPanch** [comment]
I guess I will have to be patient and somehow circumvent the missing release for now, thanks for the answer

**Comment by alexchandel** [comment]
@MischaPanch You can take a crack at fixing the two failing tests, if you have time.

The failing unit test blocking 3.14 is `test_getting_overloaded_method_binding_does_not_leak_memory`, [here](https://github.com/pythonnet/pythonnet/actions/runs/23580361629/job/68661722526) .

```py
    def test_getting_overloaded_method_binding_does_not_leak_memory():
        """Test that managed object is freed after calling overloaded method. Issue #691"""
    
        from PlainOldNamespace import PlainOldClass
    
        import psutil, os, gc, clr
    
        process = psutil.Process(os.getpid())
        processBytesBeforeCall = process.memory_info().rss
        print("\n\nMemory consumption (bytes) at start of test: " + str(processBytesBeforeCall))
    
        iterations = 500
        for i in range(iterations):
            PlainOldClass().OverloadedMethod.Overloads[int]
    
        gc.collect()
        System.GC.Collect()
    
        processBytesAfterCall = process.memory_info().rss
        print("Memory consumption (bytes) at end of test: " + str(processBytesAfterCall))
        processBytesDelta = processBytesAfterCall - processBytesBeforeCall
        print("Memory delta: " + str(processBytesDelta))
    
        bytesAllocatedPerIteration = pow(2, 20)  # 1MB
        bytesLeakedPerIteration = processBytesDelta / iterations
    
        # Allow 50% threshold - this shows the original issue is fixed, which leaks the full allocated bytes per iteration
        failThresholdBytesLeakedPerIteration = bytesAllocatedPerIteration / 2
    
>       assert bytesLeakedPerIteration < failThresholdBytesLeakedPerIteration
E       assert 903208.96 < 524288.0

tests\test_method.py:1015: AssertionError
---------------------------- Captured stdout call -----------------------------


Memory consumption (bytes) at start of test: 163160064
Memory consumption (bytes) at end of test: 614764544
Memory delta: 451604480
=========================== short test summary info ===========================
FAILED tests/test_method.py::test_getting_overloaded_method_binding_does_not_leak_memory - assert 903208.96 < 524288.0
============= 1 failed, 465 passed, 5 skipped, 1 xpassed in 5.02s =============
```

Additionally, the mono tests fail with an internal error [here](https://github.com/pythonnet/pythonnet/actions/runs/23580361629/job/68661722505),

```py
  Determining projects to restore...
  All projects are up-to-date for restore.
  Python.Runtime -> /Users/runner/work/pythonnet/pythonnet/pythonnet/runtime/Python.Runtime.dll
  Python.Test -> /Users/runner/work/pythonnet/pythonnet/src/testing/bin/Debug/netstandard2.0/Python.Test.dll
  Python.Test -> /var/folders/t5/f77_gwnj6p95qxy9py3fckx00000gn/T/tmpe58flof0/
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/pythonnet/__init__.py", line 75, in _create_runtime_from_spec
INTERNALERROR>     return clr_loader.get_mono(**params)
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/clr_loader/__init__.py", line 78, in get_mono
INTERNALERROR>     impl = Mono(
INTERNALERROR>         # domain=domain,
INTERNALERROR>     ...<7 lines>...
INTERNALERROR>         set_signal_chaining=set_signal_chaining,
INTERNALERROR>     )
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/clr_loader/mono.py", line 36, in __init__
INTERNALERROR>     self._version: str = initialize(
INTERNALERROR>                          ~~~~~~~~~~^
INTERNALERROR>         config_file=optional_path_as_string(config_file),
INTERNALERROR>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>     ...<8 lines>...
INTERNALERROR>         trace_level=trace_level,
INTERNALERROR>         ^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>     )
INTERNALERROR>     ^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/clr_loader/mono.py", line 146, in initialize
INTERNALERROR>     _MONO = load_mono(libmono)
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/clr_loader/ffi/__init__.py", line 49, in load_mono
INTERNALERROR>     return ffi.dlopen(path_str, ffi.RTLD_GLOBAL)
INTERNALERROR>            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/cffi/api.py", line 150, in dlopen
INTERNALERROR>     lib, function_cache = _make_ffi_library(self, name, flags)
INTERNALERROR>                           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/cffi/api.py", line 834, in _make_ffi_library
INTERNALERROR>     backendlib = _load_backend_lib(backend, libname, flags)
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/cffi/api.py", line 829, in _load_backend_lib
INTERNALERROR>     raise OSError(msg)
INTERNALERROR> OSError: cannot load library '/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib': dlopen(/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib, 0x000A): tried: '/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib' (no such file), '/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.dylib'
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/_pytest/main.py", line 314, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/_pytest/config/__init__.py", line 1159, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/pluggy/_hooks.py", line 534, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/.venv/lib/python3.14/site-packages/pluggy/_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/tests/conftest.py", line 87, in pytest_configure
INTERNALERROR>     import clr
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/clr.py", line 6, in <module>
INTERNALERROR>     load()
INTERNALERROR>     ~~~~^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/pythonnet/__init__.py", line 133, in load
INTERNALERROR>     set_runtime_from_env()
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~^^
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/pythonnet/__init__.py", line 114, in set_runtime_from_env
INTERNALERROR>     runtime = _create_runtime_from_spec(spec)
INTERNALERROR>   File "/Users/runner/work/pythonnet/pythonnet/pythonnet/__init__.py", line 90, in _create_runtime_from_spec
INTERNALERROR>     raise RuntimeError(
INTERNALERROR>     ...<2 lines>...
INTERNALERROR>     ) from exc
INTERNALERROR> RuntimeError: Failed to create a .NET runtime (mono) using the
INTERNALERROR>                 parameters {}.
```

**Comment by rayhaze** [comment]
Following.

**Comment by filmor** [comment]
The blocker is https://github.com/pythonnet/pythonnet/issues/2696 and me travelling. I will get back to this in a week or so. If someone contributes patches for the blocker and the remaining CI issues, that would of course help a lot :)

**Comment by alexchandel** [comment]
@filmor Do you think that CI failure (`test_getting_overloaded_method_binding_does_not_leak_memory`) is a genuine memory leak?

**Comment by dorfman2** [comment]
Bumping this. Using the pre-release version for now.

**Comment by filmor** [comment]
https://github.com/pythonnet/pythonnet/releases/tag/v3.1.0-rc1 is hopefully the final release candidate. Please test it thoroughly. I will ensure that the changelog is up to date and release it as 3.1.0 next weekend, provided no blockers appear in the meantime.

**Comment by ghaarsma** [comment]
Looking forward to the official release. We tested our application with V3.1.0-rc1 and found no issues.

Thanks @filmor , for all your work in getting a Python 3.14 release out the door.

**Comment by wrichardsonafmil** [comment]
Hello just wanted to get a status on when 3.1.0 is slotted to be released? Thank you!

**Comment by freakboy3742** [comment]
@filmor I've done another pass of testing with 3.1.0rc1 with Toga's test suite, and didn't spot any problems.
